
_target_: src.models.ChatGPTModel

half_precision: True

name: ${.pretrained_model_name_or_path}

pretrained_model_name_or_path: ??? # local path to the model, should be specified at runtime

output_dir: ${output_dir}
openai_api_key: "$API_KEY"

collator_parameters:
  max_input_length: ${datamodule.max_num_tokens_input}
  max_output_length: ${datamodule.max_num_tokens_target}
  padding: "longest"
  truncation: True

inference:
  chatgpt_generation_params:
    temperature: 1.0
    max_tokens: 256
    frequency_penalty: 0.0
    presence_penalty: 0.0
