# @package datamodule
defaults:
  - /datamodule/_default@_here_

task: "CP"
name: "ptb64"

dataset_target_: src.datamodules.CPInputDataset
data_dir: ${data_dir}/${datamodule.task}/ptb

gzipped: False

max_num_tokens_input: 1920 # 2048-128=1920
max_num_tokens_target: 64 # 256 will filter 576 over 2416 (23.8%)

dataset_parameters:
  test:
    dataset:

      seed: ${seed}
      prompter: # recursive instantiation: https://hydra.cc/docs/advanced/instantiate_objects/overview/#recursive-instantiation
        _target_: src.prompting.prompter.Prompter.from_local
        dir_path: ${assets_dir}/prompts/${datamodule.task}/${datamodule.prompter}
        num_demo: 4
      load_dataset_params:
        path: ${datamodule.data_dir}/ptb-test.jsonl
        bounds:
          text: ${datamodule.max_num_tokens_input}
          target: ${datamodule.max_num_tokens_target}
