# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

job_logging:
  handlers:
    file:
      # relative to the job log directory
      filename: ${hydra:runtime.output_dir}/stdout_${hydra.job.name}_${now:%Y-%m-%d}_${now:%H-%M-%S}.log

# output paths for hydra logs
run:
  dir: logs/${logs_subfolder}/runs/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}

sweep:
  dir: logs/${logs_subfolder}/multiruns/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}
# Set cuda visible devices from command line: export CUDA_VISIBLE_DEVICES=0;python ...
# Or python run.py +hydra.job.env_set.CUDA_VISIBLE_DEVICES="3'
