_target_: pytorch_lightning.Trainer

# This is only for inference

devices: ???
max_steps: ???

accelerator: "auto"
strategy: "fsdp_cpu_offload"


num_sanity_val_steps: 0

precision: 16

enable_progress_bar: True
