# @package _global_

# Activate the debug config through the CLI (e.g. `python ... +debug=fast`)

defaults:
  - hydra: inference
  - datamodule: ???
  - model: ???
  - trainer: ???
  - logger:
    - wandb
    - csv

  - optional local: default
  - _self_

# path to work directory
work_dir: ${hydra:runtime.cwd}

# path to data directory
data_dir: ${work_dir}/data

pgf_dir: ${work_dir}/assets/pgf

assets_dir: ${work_dir}/assets

# path to output directory, created dynamically by hydra
output_dir: ${hydra:runtime.output_dir}

ignore_warnings: False
print_config: True

# Seed used to seed everything in the beginning of the run script and to fix randomness in dataset
seed: 123

# determines the log directory's parent folder
logs_subfolder: inference

# determines the log directory's identifier
#run_name: ???

run_name: Task_${task}_Model_${model.name}_Datamodule_${datamodule.name}_Constraint_${oc.select:model.gf_constraint_module.name,null}
