defaults:
  - rebel

data_dir: ${data_dir}/ie/${.name}


apply_ordering_heuristic: False # We will load a dataset that is already ordered
gzipped: True

dataset_parameters:
  train:
    dataset:
      load_dataset_params:
        split: "train"
  val:
    dataset:
      load_dataset_params:
        split: "val"
  test:
    dataset:
      load_dataset_params:
        split: "test"
