defaults:
  - _default

name: "sdg_code_davinci_002"

batch_size: 4
num_workers: 4

dataset_target_: src.datamodules.IEInputDataset
data_dir: ${data_dir}/sdg_code_davinci_002


apply_ordering_heuristic: True
gzipped: True
