defaults:
  - sdg_text_davinci_003

name: "sdg_text_davinci_003"

data_dir: ${data_dir}/ie/${.name}

apply_ordering_heuristic: False # We will load a dataset that is already ordered
gzipped: True

dataset_parameters:
  train:
    dataset:
      load_dataset_params:
        split: "train_ordered"
  val:
    dataset:
      load_dataset_params:
        split: "val_ordered"
  test:
    dataset:
      load_dataset_params:
        split: "test_ordered"
