defaults:
  - sdg_text_davinci_003_pc

data_dir: ${data_dir}/ie/${.name}


apply_ordering_heuristic: False # We will load a dataset that is already ordered
gzipped: True

dataset_parameters:
  test:
    dataset:
      load_dataset_params:
        split: "test_small_ordered"
