# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "post-rebuttal" # The name of the project where you're sending the new run. Default: Uncategorized runs
  name: ${run_name} # A short display name for this run, which is how you'll identify this run in the UI. Default: Randomly generated two word name
  save_dir: ${output_dir}
  offline: True # set True to store all logs only locally
  id: null # A unique ID for this run, used for resuming! See guide for resuming runs...
  entity: null # set to name of your wandb team
  log_model: False
  group: ""
  job_type: ""
  tags: []
  notes:
